spring.application.name=GatewayMS

server.port=9000

spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations[/**].allowedHeaders=*

#UserMS
spring.cloud.gateway.server.webflux.routes[0].id=UserMS
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].uri=lb://UserMS
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=TokenFilter


#ProfileMs
spring.cloud.gateway.server.webflux.routes[1].id=ProfileMs
#spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:9100
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ProfileMs
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/profile/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=TokenFilter


#AppointmentMs
spring.cloud.gateway.server.webflux.routes[2].id=Appointment
#spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:9200
spring.cloud.gateway.server.webflux.routes[2].uri=lb://Appointment
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/appointment/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=TokenFilter


#PharmacyMs
spring.cloud.gateway.server.webflux.routes[3].id=PharmacyMS
#spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:9300
spring.cloud.gateway.server.webflux.routes[3].uri=lb://PharmacyMS
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/pharmacy/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=TokenFilter


#media
spring.cloud.gateway.server.webflux.routes[4].id=media
#spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:9300
spring.cloud.gateway.server.webflux.routes[4].uri=lb://media
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/media/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=TokenFilter
